apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nroute-data-pvc
  namespace: nroute
  labels:
    app.kubernetes.io/name: nroute
    app.kubernetes.io/managed-by: manual
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nroute-output-pvc
  namespace: nroute
  labels:
    app.kubernetes.io/name: nroute
    app.kubernetes.io/managed-by: manual
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
